### ISSUE TITLE
suggestionsTransform is not run on the first time ListBox is rendered

### ISSUE THREAD

**Issue by tarngerine** [i-like-robots/react-tag-autocomplete#14]
Steps:

1. Add suggestionsTransform to add some prefix (e.g. #)
2. Focus the input
3. See the listbox rendered
4. Expected: `#` is shown
5. Actual: `#` is not shown
6. Type a character in the input
7. `#` is now shown
8. Clear the input
9. `#` is still shown

**Comment by i-like-robots** [comment]
Thanks for the report, should be easy to fix 👍

**Comment by i-like-robots** [comment]
[v7.0.0-beta.9](https://www.npmjs.com/package/react-tag-autocomplete/v/7.0.0-beta.9) has been released with the fix.
