### ISSUE TITLE
Allow resetting the input

### ISSUE THREAD

**Issue by tarngerine** [i-like-robots/react-tag-autocomplete#18]
Because the Input component is providing `value` attribute, the default HTML behavior of an `<input type="reset">` does not clear the `<input type="text">`, since HTML input does not reset when a value attr is provided or set via `setAttribute`. 

We are able to reset the `selected` prop but we cannot reset the input `value` attr as there is no prop to do so.

I can see a few ways here:

1. Change `Input.tsx` to not use `value` as a prop, but rather a `useEffect` that sets the input value imperatively. This allows the standard HTML type="reset" to clear it
2. Add a `input` prop to `<ReactTags>` that is passed to `Input.tsx`'s `value` for a fully controlled input

The latter is probably more reacty

**Comment by i-like-robots** [comment]
It's not a tested/documented feature yet but the component does have an API similar to the previous version of the component and this includes a `.clear()` method. I've made an example here:

https://github.com/i-like-robots/react-tag-autocomplete/blob/11ce2d41c8d9d3261672ab0bfb3db39ff90947fa/example/src/main.jsx#L358-L360

Would this suit your needs? The API may change but a method to clear the input will always be included.

Custom input renderers are certainly a possibility, I haven't given it much thought yet but it's certainly possible.

**Comment by tarngerine** [comment]
less about custom input renderer, more about making it a controlled input :) but this will work for now. thanks!

**Comment by i-like-robots** [comment]
I'm going to close this issue now. The input value can be get/set via [the API](https://github.com/i-like-robots/react-tag-autocomplete#api) and #36 adds the capability to provide a custom input component and therefore enable full control.
