### ISSUE TITLE
How to auto-highlight the first option

### ISSUE THREAD

**Issue by tarngerine** [i-like-robots/react-tag-autocomplete#21]
most @ mention/tag/typeahead UX on the web, auto highlights the first matching item without needing to hit arrow-down to select it. is there a way to have this behavior?

<img width="514" alt="image" src="https://user-images.githubusercontent.com/1629901/195627646-7db8ad97-9275-47c2-b3a7-84aa80a6c8a2.png">

**Comment by i-like-robots** [comment]
This would be very straightforward to add now that I've refactored the manager: https://github.com/i-like-robots/react-tag-autocomplete/compare/highlight-first-option

I'm unsure about this feature from an accessibility point of view however, such behaviour is not part of any combobox spec that I have read so I'd need to try it out.

**Comment by tarngerine** [comment]
Thank you!
