### ISSUE TITLE
startWithFirstOption doesn't update when filtering suggestions

### ISSUE THREAD

**Issue by tarngerine** [i-like-robots/react-tag-autocomplete#28]
1. Go to demo site: https://i-like-robots.github.io/react-tag-autocomplete/
2. Enable start with first option in the top demo
3. Focus input, see Afghanistan is selected
4. Type "p", see Cape Verde is selected
5. Press enter

Expected: Cape Verde added
Actual: Afghanistan added

**Comment by i-like-robots** [comment]
Thank you for the report @tarngerine and I confirm I recreate this issue too.

**Comment by tarngerine** [comment]
thank you! may i ask when could a release be made?
