### ISSUE TITLE
Prevent closing combobox when click on scrollbar

### ISSUE THREAD

**Issue by Tomas2D** [i-like-robots/react-tag-autocomplete#33]
Hello, I have noticed that when I open the combo box and try to click on the scrollbar to scroll through the results, the combo box will get closed.

![Snímek obrazovky 2023-02-02 v 13 40 01](https://user-images.githubusercontent.com/15633909/216327516-924a8a7b-880e-455a-8982-6a7f0216bc16.png)

**Comment by i-like-robots** [comment]
Thanks for raising this @Tomas2D, it's definitely a bug. The listbox is not focusable so that's why it's closing - it could be resolved by adding a `tabindex` to the listbox but there are a few quirks to the focus behaviour I need to look closely at.

**Comment by Tomas2D** [comment]
I fixed that in #34, but sure, if there is better a way, why not.

**Comment by i-like-robots** [comment]
Fixed in [3aeb3bc](https://github.com/i-like-robots/react-tag-autocomplete/commit/3aeb3bc874c786fb77f4b3d63176cce80874e34d)
