### ISSUE TITLE
Custom tags example only allows one tag

### ISSUE THREAD

**Issue by juanramoncarceles** [i-like-robots/react-tag-autocomplete#4]
Hi!

This might be a bug because I can't add more than one tag in the "custom tags" example.

https://github.com/i-like-robots/react-tag-autocomplete/blob/973d6a361441f9875e80d8347a8721a108fa5c86/example/src/main.jsx#L115-L165

When I add a second tag the first one gets removed.

I would like to use this component in a project with React 18, that's why I tried the beta version instead of the stable one.

**Comment by i-like-robots** [comment]
Thank you, good spot. The custom tags are being created with a `null` ID so it's getting confused.
