### ISSUE TITLE
TypeError: _a.scrollIntoView is not a function

### ISSUE THREAD

**Issue by ggilley** [i-like-robots/react-tag-autocomplete#47]
I'm trying to use react testing library to test an interface that uses the combo box.

`await userEvent.type(tagsField, "bananas{arrowdown}{enter}");`

I get an error 

```
    console.error
      Error: Uncaught [TypeError: _a.scrollIntoView is not a function]
```

If I add `skipClick: true` like I see in your tests, the input doesn't go into the tagsField because another field is selected.
Trying to click the field first

`await userEvent.click(tagsField);`

I get the same error

The code works fine in the browser, it's just failing in the unit test. Any ideas?

**Comment by i-like-robots** [comment]
Thanks for your question @ggilley - `scrollIntoView` isn't supported by JSDOM so in the tests for the component it has been mocked out manually: https://github.com/i-like-robots/react-tag-autocomplete/blob/de2d9a4b76b7349e44d1e9953fe7c329bf17c162/src/test/Harness.tsx#L10C1-L12
