### ISSUE TITLE
Get `TagRendererProps.onDelete` back in v7, to use as `TagComponentProps.onDelete` from v6 

### ISSUE THREAD

**Issue by acelaya** [i-like-robots/react-tag-autocomplete#48]
## Describe the solution you'd like

In v6 of this component, `TagComponentProps` had an `onDelete` prop that came in handy when using `tagComponent` to customize how tags were rendered.

The new `renderTag` prop, which according to the [migration guide](https://github.com/i-like-robots/react-tag-autocomplete/blob/de2d9a4b76b7349e44d1e9953fe7c329bf17c162/migration-guide.md#changes-to-render-props) is `tagComponent`'s replacement, does not provide `onDelete` anymore.

## Describe alternatives you've considered

I considered using the new API which is exposed via ref, but it does not include a method to delete a tag, but only to select one.

## Additional context

This property was useful if custom tag rendering also had its own delete button.

**Comment by i-like-robots** [comment]
Thanks for your question @acelaya - the `onSelect` callback toggles the tag selection. So calling `onSelect` from a selected tag will delete it. Sorry this isn't clear, I will look to improve the documentation here.

**Comment by acelaya** [comment]
Oh, I see. Thanks! That should do the trick
