### ISSUE TITLE
Consider strict TS

### ISSUE THREAD

**Issue by genox** [i-like-robots/react-tag-autocomplete#5]
Hi,

While using this component I get numerous TS errors during builds. They seem to be related to the fact that this is written with strict mode disabled in TS (https://kovalevski.net/what-is-strict-mode-in-typescript-and-why-and-when-you-should-use-it/).

Consider writing the component with strict mode enabled.

All the best, Oliver

**Comment by i-like-robots** [comment]
I've published v7.0.0-beta.6 which provides a generated type declaration file instead of relying on the source code for type information.

I've also fixed all of the `noImplicitAny` warnings and errors in the source code to help move in a stricter direction.
