### ISSUE TITLE
Ignore tags added twice, instead of removing them

### ISSUE THREAD

**Issue by acelaya** [i-like-robots/react-tag-autocomplete#50]
## Describe the solution you'd like

> I'm not reporting this as a bug, even though for me it's a bit counter-intuitive behavior, because I see it being used consciously in the [countries example](https://i-like-robots.github.io/react-tag-autocomplete/).

Currently, when the same tag is added twice, it results in the tag getting actually removed. I guess this is because of the `Api.select()` method nature, which actually toggles tags.

[duplicated-tags.webm](https://github.com/i-like-robots/react-tag-autocomplete/assets/2719332/23c2969d-d37d-4280-b388-d3d293030ebf)

When using this library's v6, tags where actually passed twice to the `onAddition` callback, and it was easy to ignore duplicates by using a `Set`.

Now, if you actually want to ignore duplicates, instead of getting them removed, there's no easy workaround unless several event handlers are overwritten.

Because of this, it would be great to support an option disabling the removal on duplicated tags.

## Describe alternatives you've considered

I have tried working around this via custom event handlers + API ref, but nothing seems to allow covering all ways to add tags (different keys, clicking on suggestions, selecting suggestions via keyboard, etc).

**Comment by i-like-robots** [comment]
Thank you for the the detailed report and video @acelaya 

The tags are [matched by their `value`](https://github.com/i-like-robots/react-tag-autocomplete/blob/main/src/lib/tagUtils.ts#L13-L15) so a workaround may be ensure the created tags have a unique value assigned to them.

I've had a think about potential options to customise this behaviour and I haven't yet thought of anything consistent. For example, adding an option to [skip the tag matching](https://github.com/i-like-robots/react-tag-autocomplete/blob/main/src/hooks/useManager.ts#L164-L166) would be easy but such an option would dramatically alter how the component functions when enabled.

**Comment by acelaya** [comment]
Thanks for the explanation. Understanding the context clarifies the behavior a lot.

> The tags are matched by their value so a workaround may be ensure the created tags have a unique value assigned to them.

This is actually not a bad idea.

I'm only using the label, so altering the value shouldn't have any impact on my implementation. I will give it a try.

**Comment by acelaya** [comment]
I can confirm using a unique value for added tags while the label is kept the same, is a good way to work around this.

Then a `Set` can be used to get rid of duplicates, so the behavior is the one I originally described.

This workaround is simple enough, so I'll close this issue.

**Comment by acelaya** [comment]
BTW, I haven't seen any way to sponsor this project. Do you somehow accept sponsoring or donations?
