### ISSUE TITLE
Render the listbox with a portal

### ISSUE THREAD

**Issue by phiter** [i-like-robots/react-tag-autocomplete#52]
## Describe the solution you'd like

Material UI renders its dropdown's listbox somewhere else in the page using a portal. This makes it possible to use the dropdown inside dialogs with it being able to overflow the dialog.  

Example:
![image](https://github.com/i-like-robots/react-tag-autocomplete/assets/12252332/85b0dcaa-481a-4381-911e-8dfb61939d2f)

Currently in react-tag-autocomplete, this isn't possible, so if you use the component inside a dialog, it doesn't overflow properly.

In our application, the dropdown doesn't go over the dialog's footer, because the dialog's body has `overflow: auto`.

![image](https://github.com/i-like-robots/react-tag-autocomplete/assets/12252332/ea109c93-fcf4-44f3-bd31-a4a240157571)

Using a portal to render the dropdown near the root element should allow this behavior.

**Comment by phiter** [comment]
By the way, if this is implemented: https://github.com/i-like-robots/react-tag-autocomplete/issues/19 We can probably manage the positioning of the listbox ourselves. The way it is right now it's impossible to do.

**Comment by i-like-robots** [comment]
Thanks for the suggestion @phiter, this isn't something I'd considered.

Adding a custom renderer for the list box would be very straightforward and I believe would enable this. Would you be interested in contributing this change?
