### ISSUE TITLE
Selecting an option would cause a scroll jump if page is horizontally scrollable

### ISSUE THREAD

**Issue by mohsentaleb** [i-like-robots/react-tag-autocomplete#54]
## Expected behaviour
Page should keep its horizontal scrolling position when user selects from the options list.

If page using this component has horizontal scrollbars, when user selects an option from the list, page scroll jumps due to [this line](https://github.com/i-like-robots/react-tag-autocomplete/blob/53d08039fe3ab95950939cb4c6cd300d4aecb420/src/hooks/useOption.ts#L30) in `useOptions.ts`

## Current behaviour
The whole page's scroll position changes.

## Steps to Reproduce
1. Go to your [demo page](https://i-like-robots.github.io/react-tag-autocomplete/)
2. Inspect the page source and go to Elements tab
3. Add an arbitrary width to the page container to make it horizontally scrollable.  `<main class="container">` -> `<main class="container" style="width:4000px">`
4. From the demo autocomplete component included in the page, try selecting an option

**Comment by i-like-robots** [comment]
Thank you for the report @mohsentaleb, I am able to reproduce this issue following your instructions.

**Comment by mohsentaleb** [comment]
@i-like-robots You don't need to provide the optional param `inline: start` to `scrollIntoView` as just bringing the selected item vertically into view would suffice.

I've made an example here with 3 different usages of `scrollIntoView`: 
https://jsfiddle.net/a2w6gscf/

Scroll all the way down until you reach to that button and do 3-5 more pixels of scrolling so that half of the button would be visible on the page then hit the button.

**Comment by i-like-robots** [comment]
Thanks for the additional details @mohsentaleb.

Removing `inline: "start"` does not appear to alter the current behaviour of the component - at least not in my testing.

Removing all options from the `.scrollIntoView()` call results in the highlighted option also being aligned to the window which is incorrect.

Refactoring the effect to use `.scrollTo()` does resolve the issue reported but I'll need to test this approach further.
