### ISSUE TITLE
DelimiterKeys is not working

### ISSUE THREAD

**Issue by Vincent59** [i-like-robots/react-tag-autocomplete#57]
Hello there!

I don't know if it's just me but the 'delimiterKeys' don't seem to work.
My code is looking like this:
 ```
 <ReactTags
    allowNew
    labelText="Tags:"
    selected={selectedTag}
    suggestions={[]}
    onAdd={onAdd}
    onDelete={onDelete}
    delimiterKeys={["Enter"]}
    noOptionsText="No matching tags"
    newOptionText={`Add Tag ${newTageName}`}
    onInput={((e) => setNewTageName(e))}
  />
```
When i press 'Enter', nothing happens. On the demo, it just work when you type the full tag name found in suggestions.

**Comment by i-like-robots** [comment]
I'm not aware of any issue with the `delimiterKeys` option, if you do find one then please do include a reproducible example for me to take a look at.

**Comment by mikalai-sauchanka** [comment]
It doesn't work until there's at least one selected tag. Here's an example: https://codesandbox.io/p/sandbox/react-tag-autocomplete-6l43qm?file=%2Fsrc%2FApp.js
