### ISSUE TITLE
DelimeterKeys doesn't work when selected value is empty array

### ISSUE THREAD

**Issue by mikalai-sauchanka** [i-like-robots/react-tag-autocomplete#63]
DelimeterKeys doesn't work until at least one tag has been added by clicking the dropdown. Here's an example: https://codesandbox.io/p/sandbox/react-tag-autocomplete-6l43qm?file=%2Fsrc%2FApp.js

**Comment by i-like-robots** [comment]
Thanks for sharing the demo @mikalai-sauchanka 

When the `allowNew` prop is enabled a new tag can only be created when selecting the new tag option from the listbox. In the code you provided the new tag option remains selected. If you'd like to reset the listbox state after adding a tag you can use the `collapseOnSelect` option.
