### ISSUE TITLE
Broken "Async suggestions" demo

### ISSUE THREAD

**Issue by Tomas2D** [i-like-robots/react-tag-autocomplete#7]
The `Loading....` message never shows up, tried also on my project and it looks like that the changed prop does not trigger component re-render.

```
const noOptionsText =
    state.isBusy && !state.suggestions.length ? 'Loading...' : 'No breweries found'`
```

https://i-like-robots.github.io/react-tag-autocomplete/

Thanks

**Comment by Tomas2D** [comment]
I find out a workaround by adding disabled option with the text `Loading`, however it works I think that we should have an option to choose the `newOption` position, it should be either `start` on `end`. What do you think?

**Comment by i-like-robots** [comment]
Thanks for the report and for your suggestions. I've had a look into this now and I can see that the `newTagOption` and `noTagsOption` methods are not being updated within the main manager state. I can make changes to fix this but I've always felt the internal options had quite a crude solution that I've never been happy with so I'll have a think how this may be better implemented.

**Comment by i-like-robots** [comment]
I've merged a refactor of the state manager to avoid copying props into state and derive values for options on the fly. This resolves the bug reported but the demo could still be improved in a number of ways.
