### ISSUE TITLE
Selected tags list customisation

### ISSUE THREAD

**Issue by ellunium** [i-like-robots/react-tag-autocomplete#70]
Is it currently possible to customise the how the selected tags list is rendered? Maybe it can be done using renderRoot?

If not, would it be possible to add a renderSelectedTagsList prop?

Thank you!

**Comment by i-like-robots** [comment]
Thanks for your question @ellunium. 

That sounds like a good idea, I'd welcome any contributions to support this request.

**Comment by ellunium** [comment]
Thanks for the reply @i-like-robots ! 

I'm not sure I can do it or if I have enough knowledge to make the contribution myself, but I will give it a try in a fork and share.

**Comment by i-like-robots** [comment]
Resolved via #71

**Comment by i-like-robots** [comment]
Released as [v.7.3.0](https://github.com/i-like-robots/react-tag-autocomplete/releases/tag/v7.3.0)
