### ISSUE TITLE
Unable to add custom tag ui

### ISSUE THREAD

**Issue by poonam-tru** [i-like-robots/react-tag-autocomplete#8]
Can you please let me know, how can i add own custom ui component as prop in V7 beta.
As currently the behaviour is , on click tag anywhere it is deleted. As I want to **delete** tag, only click via **delete icon**.

**Comment by i-like-robots** [comment]
Please refer to the roadmap [here](https://github.com/i-like-robots/react-tag-autocomplete/issues/6) which shows this feature as not yet complete.

As explained further down in that issue I have implemented most of the code required and the docs too but I've not yet written any tests. I've got a few weeks off coming up so I plan on finishing this feature during that time.

**Comment by i-like-robots** [comment]
@poonam-tru I've published [v7.0.0-beta.7](https://www.npmjs.com/package/react-tag-autocomplete/v/7.0.0-beta.7) which exposes 3 new props: `renderLabel`, `renderOption` and `renderTag`. As mentioned previously they are not tested and they are not documented but now you can use them. Below is the documentation which I plan publish when the features are ready but you can also refer to the default implementations in the source code:

---

#### renderLabel (optional)

Optional custom label component to render. Receives the label text as children, required label attributes, and [`classNames`](#classNames-optional) as props. Defaults to `null`.


```js
function CustomLabel({ children, classNames, ...labelProps }) {
  return (
    <div className={classNames.label} {...labelProps}>
      {children}
    </div>
  )
}
```

#### renderOption (optional)

Optional custom option component to render. Receives the option, pre-rendered option text as children, required option attributes, and [`classNames`](#classNames-optional) as props. Defaults to `null`.

```js
function CustomOption({ children, classNames, option, ...optionProps }) {
  const classes = [
    classNames.option,
    option.active ? 'is-active' : '',
    option.selected ? 'is-selected' : ''
  ]

  return (
    <div className={classes.join(' ')} {...optionProps}>
      {children}
    </div>
  )
}
```

#### renderTag (optional)

Optional custom tag component to render. Receives the selected tag, required tag attributes, and [`classNames`](#classNames-optional) as props. Defaults to `null`.

```js
function CustomTag({ classNames, tag, ...tagProps }) {
  return (
    <button type="button" className={classNames.tag} {...tagProps}>
      <span className={classNames.tagName}>{tag.label}</span>
    </button>
  )
}
```

**Comment by poonam-tru** [comment]
Ok, Superb!

**Comment by poonam-tru** [comment]
Hey, Is there any option to clear all the suggestions from the input of
react tag?

Case:  I have a delete all button, I want to delete all suggestions on
click that button.
Case: I am using the react tag in map loop.

**Comment by i-like-robots** [comment]
[v7.0.0-beta.9](https://www.npmjs.com/package/react-tag-autocomplete/v/7.0.0-beta.9) now includes the documentation for the render props.
