### ISSUE TITLE
Unable to remove the all suggestion tags.

### ISSUE THREAD

**Issue by poonam-tru** [i-like-robots/react-tag-autocomplete#9]
Hey, Is there any option to clear all the suggestions from the input of react tag and clear input field? 

Case:  I have a delete all button, I want to delete all suggestions on click that button.
Case: How to clear the input field on click custom clear button.

**Comment by i-like-robots** [comment]
>  I have a delete all button, I want to delete all suggestions on click that button.

Do you mean selected tags? Either way, both selected tags and suggested tags are fully in your control.

> How to clear the input field on click custom clear button.

The last few versions of the component have had [an API](https://github.com/i-like-robots/react-tags/#api) with a method to clear the input. Internally these methods still exist but I haven't tried to expose them as part of the public interface because I have never needed to use them in my work! Your use case makes sense though so I may reconsider this.

**Comment by i-like-robots** [comment]
I've opened a draft pull request which shows my progress exposing a public API but it will need some more work before it is finalised: https://github.com/i-like-robots/react-tag-autocomplete/pull/11

**Comment by poonam-tru** [comment]
Yes, I mean the same , as you mentioned. So, I want,  i need the props
through which i can handle deletion of selected tags.

**Comment by poonam-tru** [comment]
So, How long will it take to merge? I need the things asap, because it
breaks my code in some cases.

**Comment by i-like-robots** [comment]
> through which i can handle deletion of selected tags.

The the selected tags are stored by the implementor and passed to `<ReactTags>` as a prop so clearing them is not something which can be controlled within this component. A clear all button could look something like this however:

```js
const [selected, setSelected] = useState([])

const onAdd = useCallback(
  (newTag) => {
    setSelected([...selected, newTag])
  },
  [selected]
)

const onDelete = useCallback(
  (index) => {
    setSelected(selected.filter((_, i) => i !== index))
  },
  [selected]
)

<ReactTags
  onAdd={onAdd}
  onDelete={onDelete}
  selected={selected}
  suggestions={suggestions}
/>
<button onClick={() => setSelected([])}>Clear all</button>
```

> So, How long will it take to merge? I need the things asap

Like the custom render props I'm happy to release what I have as undocumented and untested, with the caveat that these features could change at any time before the stable release.

I don't currently need this feature so it will be released when I feel like it but I would welcome any contributions to help speed things up.

**Comment by poonam-tru** [comment]
Hi matt,

I have tested it and installed it, But I am unable to clear the input with
the same as you shared.Can you please let me know what is happening? As I
am afraid, That its not working.

I have used this installation: npm i ***@***.***
[image: image.png]
